### PR TITLE
Release series object

### PR DESCRIPTION
**Pull request by garsiden**
Minor changes to data structures.

### CODE REVIEW

**Comment by irlndts** [comment]
hi man, thank you for your pr. Can you give a link to any example with Series in discogs database please?

**Comment by garsiden** [comment]
Artem,

Of course; I should have thought to include one in the PR.

https://api.discogs.com/releases/4659159

And a link to a release that has a description field in a "Matrix / Runout"
identifier:

https://api.discogs.com/releases/4728859

Regards,

Nigel

**Comment by irlndts** [comment]
Cool, thanks!

**Comment by irlndts** [comment]
Btw, if you found the lib useful can you give a star to it please?

**Comment by garsiden** [comment]
Artem,

Useful enough that I've made my first contribution, albeit minor, to a
Github project, so duly starred!

Briefly, if I can, it may interest you how your lib is being used. You may
know of the stevehoffman.tv music forum, where there is a thread regarding
a series of budget vinyl re-issues from the late 80s, Original Jazz
Classics, and part of the discussion is about when the series went from an
analogue source to digital. The original mastering engineer was George Horn
so an LP with his initials as part of the matrix number would indicate it
is analogue. I've used your lib to retrieve LPs on the OJC label and select
those where the Matrix/Runout information has been added to try and provide
some sort of time-line, so this why the extra description field is useful.

Regards,

Nigel

**Pull request merged**
